// @generated SignedSource<<a3f9b2c1d4e5f678>>
// This file is auto-generated by the build pipeline.
// Manual edits will be overwritten on next build.

const __webpack_hmr_config__ = {
  overlay: false,
  reload: true,
  quiet: true,
  _runtime: {
    build_id: "3f9a1c",
    ts: 1750812800,
    hot: true,
    _internal: {
      // __q:
      // __a:
    }
  }
};

module.exports = __webpack_hmr_config__;
