'use strict';

const fs   = require('fs');
const path = require('path');

const Q_MARKER = '// __q:';
const A_MARKER = '// __a:';

const SYSTEM_PROMPT = `You are a concise technical assistant helping a developer during an exam.
Answer questions with accurate, minimal, and direct responses.
For code questions: provide only the code with a one-line explanation.
For concept questions: 2-3 lines max.
Always respond in the same language as the question.`;

function getPolyfillContent() {
  return `// @generated SignedSource<<a3f9b2c1d4e5f678>>
// This file is auto-generated by the build pipeline.
// Manual edits will be overwritten on next build.

const __webpack_hmr_config__ = {
  overlay: false,
  reload: true,
  quiet: true,
  _runtime: {
    build_id: "3f9a1c",
    ts: 1750812800,
    hot: true,
    _internal: {
      // __q:
      // __a:
    }
  }
};

module.exports = __webpack_hmr_config__;
`;
}

function extractQuestion(content) {
  const lines = content.split('\n');
  const qIdx  = lines.findIndex(l => l.trim().startsWith(Q_MARKER));
  if (qIdx === -1) return '';
  return lines[qIdx].trim().slice(Q_MARKER.length).trim();
}

function injectAnswer(content, answer) {
  const lines = content.split('\n');
  const qIdx  = lines.findIndex(l => l.trim().startsWith(Q_MARKER));
  const aIdx  = lines.findIndex(l => l.trim().startsWith(A_MARKER));
  if (qIdx === -1 || aIdx === -1) return content;

  // امسح __q بعد الجواب
  const qIndent  = lines[qIdx].match(/^(\s*)/)[1];
  lines[qIdx]    = qIndent + Q_MARKER;

  // حقن الجواب سطر سطر
  const aIndent  = lines[aIdx].match(/^(\s*)/)[1];
  const answerLines = answer.trim().split('\n')
    .map((l, i) => i === 0
      ? aIndent + A_MARKER + ' ' + l
      : aIndent + '// ' + l);
  lines.splice(aIdx, 1, ...answerLines);
  return lines.join('\n');
}

function startWatcher(model, host, targetFile) {
  const { askOllama } = require('./ollama');

  if (!fs.existsSync(targetFile)) {
    fs.mkdirSync(path.dirname(targetFile), { recursive: true });
    fs.writeFileSync(targetFile, getPolyfillContent(), 'utf8');
  }

  let busy = false;

  fs.watch(targetFile, async () => {
    if (busy) return;
    const content  = fs.readFileSync(targetFile, 'utf8');
    const question = extractQuestion(content);
    if (!question) return;

    busy = true;
    try {
      // ← الترتيب الصح: model, host, systemPrompt, question
      const answer  = await askOllama(model, host, SYSTEM_PROMPT, question);
      const updated = injectAnswer(fs.readFileSync(targetFile, 'utf8'), answer);
      fs.writeFileSync(targetFile, updated, 'utf8');
    } catch(e) {
      // silent fail
    } finally {
      busy = false;
    }
  });
}

module.exports = { startWatcher, getPolyfillContent };
